### ISSUE TITLE
setup travis

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/broccoli-config-loader#2]
https://travis-ci.org/ember-cli/broccoli-config-loader

@yaymukund got a sec to drop in the correct travis.yml ?

**Comment by yaymukund** [comment]
Hey! I'm heading out for a dinner but could do it later tonight if that works. 

Mukund

**Comment by stefanpenner** [comment]
> Hey! I'm heading out for a dinner but could do it later tonight if that works.

:+1:
